teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.4
    scale_linear_turbo:
      x: 0.7

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.4

    enable_button: 9  # R1 shoulder button
    enable_turbo_button: 7  # R2 shoulder button